project: MolSynthRL
experiment_name: RandomSearch_Uni
reaction_mode: uni
masking: reaction_valid
reward: delta_qed
max_episode_len: 5
dataset:
  test_file: GenMolRL/data/Uni/reactants_test.pkl
  templates_file: GenMolRL/data/Uni/templates_unimolecolar_explicit.pkl
env:
  invalid_reaction_penalty: -1.0
  reward_round_digits: 3
training:
  seed: 42
search:
  max_paths: 100
  max_attempts: 1000
  max_reactions: 10000
  max_r2_per_template: 100
  results_file: GenMolRL/runs/random_search_uni_results.txt
  overwrite_results: true
  use_wandb: true
